services:
  varnish:
    image: varnish:7.4
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - node

  node:
    image: node:20
    working_dir: /home/node/app
    # user: node
    init: true
    volumes:
      - ../../:/home/node/app
    command: corepack pnpm --filter esi-express dev
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_ESI_SECRET=${REACT_ESI_SECRET:-ChangeMe}
    restart: unless-stopped

volumes:
  node_modules:
  node_modules-lib:
  node_modules-express:
