name: Tests / Lint

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    name: Run tests with Node.js ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm --filter react-esi install --frozen-lockfile
      - run: pnpm --filter react-esi build
      - run: pnpm --filter react-esi test
      - run: pnpm --filter react-esi lint
